name: Generate Slots

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Call endpoint
        run: |
          curl -f -sS -X POST https://nonerroneously-nonelliptic-shaunna.ngrok-free.dev/api/slots/generate \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"